#!/usr/bin/env python3
"""Bundle the existing static site into a self-contained Sites Worker."""

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "site"
OUT = ROOT / "dist" / "server" / "index.js"
MIME = {
    ".html": "text/html; charset=utf-8",
    ".js": "text/javascript; charset=utf-8",
    ".css": "text/css; charset=utf-8",
}


def main() -> None:
    files = {}
    for path in SOURCE.iterdir():
        if path.is_file() and path.suffix in MIME:
            files["/" + path.name] = {
                "body": path.read_text(encoding="utf-8"),
                "type": MIME[path.suffix],
            }
    required = {"/index.html", "/app.js", "/model.js", "/screens.js", "/styles.css"}
    missing = required - files.keys()
    if missing:
        raise SystemExit(f"Missing site files: {', '.join(sorted(missing))}")

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(
        "// Generated by scripts/build_site.py from site/. Do not edit.\n"
        + "const files = "
        + json.dumps(files, ensure_ascii=False, separators=(",", ":"))
        + ";\n"
        + "export default { async fetch(request) {\n"
        + "  if (request.method !== 'GET' && request.method !== 'HEAD') return new Response('Method not allowed', { status: 405 });\n"
        + "  const path = new URL(request.url).pathname;\n"
        + "  const file = files[path === '/' ? '/index.html' : path];\n"
        + "  if (!file) return new Response('Not found', { status: 404 });\n"
        + "  return new Response(request.method === 'HEAD' ? null : file.body, { headers: { 'content-type': file.type, 'x-content-type-options': 'nosniff' } });\n"
        + "} };\n",
        encoding="utf-8",
    )
    print(f"Built {len(files)} site files")


if __name__ == "__main__":
    main()
